<!DOCTYPE html>
<html>

<head>

    <title><?=$title; ?></title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="all" />

</head>

<body>
    <h1><?=$title; ?></h1>
<?=$pages;?>
<?php if (isset($items) && (count($items) > 0)): ?>
<?php foreach ($items as $item): ?>
    <div class="item-div">
        <h3><?=$item->title; ?></h3>
<?php if (isset($item->uri)): ?>
        <p><a href="<?=$item->uri; ?>"><?=$item->uri; ?></a></p>
<?php endif; ?>
    </div>
<?php endforeach; ?>
<?php endif; ?>
</body>

</html>
