<?php include $phireHeader; ?>
    <h1 class="tags-header"><?=$title; ?> : <span id="title-span"><?=$tag_title; ?></span></h1>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'tags', 'add')): ?>
        <nav><a href="<?=$phireUri; ?>/tags/add">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri; ?>/tags">Back</a></nav>
    </nav>
<?=$form; ?>
<?php include $phireFooter; ?>
