<?php include $phireHeader; ?>
    <h1 class="tags-header"><?=$title; ?></h1>
<?php if (count($tags) > 0): ?>
<?php if ($acl->isAllowed($user->role, 'tags', 'add')): ?>
    <nav id="sub-nav">
        <nav><a href="<?=$phireUri; ?>/tags/add">+ Add</a></nav>
    </nav>
<?php endif; ?>
<?php if ($acl->isAllowed($user->role, 'tags', 'remove')): ?>
    <form id="tags-form" action="<?=$phireUri . '/tags/remove'; ?>" method="post">
<?php endif; ?>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th><a href="<?=$phireUri . '/tags?sort=id';?>">#</a></th>
                <th><a href="<?=$phireUri . '/tags?sort=title';?>">Title</a></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'tags', 'edit')): ?>Edit<?php else: ?>&nbsp;<?php endif; ?></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'tags', 'remove')): ?><input type="checkbox" name="checkall" id="checkall" value="rm_tags" /><?php else: ?>&nbsp;<?php endif; ?></th>
            </tr>
<?php $i = 1; ?>
<?php foreach ($tags as $tag): ?>
            <tr>
                <td><?=$tag->id; ?></td>
                <td><?=$tag->title; ?></td>
                <td><?php if ($acl->isAllowed($user->role, 'tags', 'edit')): ?><a class="edit-link" href="<?=$phireUri . '/tags/edit/' . $tag->id; ?>">Edit</a><?php else: ?>&nbsp;<?php endif; ?></td>
                <td class="text-center"><?php if ($acl->isAllowed($user->role, 'tags', 'remove')): ?><input type="checkbox" name="rm_tags[]" id="rm_tags<?=$i++; ?>" value="<?=$tag->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
            </tr>
<?php endforeach; ?>
        </table>
<?php if ($acl->isAllowed($user->role, 'tags', 'remove')): ?>
        <div id="form-footer"><input type="submit" name="submit" class="process-btn" value="Remove" /></div>
    </form>
<?php endif; ?>
<?php else: ?>
<?php if ($acl->isAllowed($user->role, 'tags', 'add')): ?>
    <nav id="sub-nav">
        <nav><a href="<?=$phireUri; ?>/tags/add">+ Add</a></nav>
    </nav>
<?php endif; ?>
    <p>There are currently no tags.</p>
<?php endif; ?>
<?php include $phireFooter; ?>
